# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/explosiveprogrammers/Dev/uiSearchConverter/UI/uiSearchConverterUI.ui'
#
# Created: Tue Dec 10 12:13:17 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(25, 40, 25, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFileDialogBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFileDialogBtn.sizePolicy().hasHeightForWidth())
        self.openFileDialogBtn.setSizePolicy(sizePolicy)
        self.openFileDialogBtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.openFileDialogBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.openFileDialogBtn.setObjectName("openFileDialogBtn")
        self.horizontalLayout.addWidget(self.openFileDialogBtn)
        self.uiPathTextEdit = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPathTextEdit.sizePolicy().hasHeightForWidth())
        self.uiPathTextEdit.setSizePolicy(sizePolicy)
        self.uiPathTextEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.uiPathTextEdit.setReadOnly(True)
        self.uiPathTextEdit.setObjectName("uiPathTextEdit")
        self.horizontalLayout.addWidget(self.uiPathTextEdit)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(10, 20, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sameFolderCheckBox = QtWidgets.QCheckBox(self.widget_2)
        self.sameFolderCheckBox.setObjectName("sameFolderCheckBox")
        self.horizontalLayout_2.addWidget(self.sameFolderCheckBox)
        self.parentFolderCheckBox = QtWidgets.QCheckBox(self.widget_2)
        self.parentFolderCheckBox.setObjectName("parentFolderCheckBox")
        self.horizontalLayout_2.addWidget(self.parentFolderCheckBox)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(25, -1, 25, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.convertUiBtn = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertUiBtn.sizePolicy().hasHeightForWidth())
        self.convertUiBtn.setSizePolicy(sizePolicy)
        self.convertUiBtn.setStyleSheet("background-color: rgb(73, 227, 163);\n"
"color: rgb(0, 0, 0);")
        self.convertUiBtn.setDefault(False)
        self.convertUiBtn.setObjectName("convertUiBtn")
        self.horizontalLayout_4.addWidget(self.convertUiBtn)
        self.verticalLayout.addWidget(self.widget_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.openFileDialogBtn.setText(QtWidgets.QApplication.translate("MainWindow", "sarchUIFile-->", None, -1))
        self.sameFolderCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "placePythonFileInSameFolder", None, -1))
        self.parentFolderCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "placePythonFileInParentFolder", None, -1))
        self.convertUiBtn.setText(QtWidgets.QApplication.translate("MainWindow", "convertUI", None, -1))

